name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install cddl 
        run: gem install --user-install cddl
      - name: set up PATH
        run: echo "$(gem env gempath | cut -d':' -f1)/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - name: test schema against test vectors
        run: make tests
      - name: test schema against any extra document
        run: make extra
